import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { NextAuthProvider, TanstackProvider } from "@/components/Provider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang='en'>
      <body className={`${inter.className} max-w-2xl mx-auto `}>
        <NextAuthProvider session={session}>
          <Navbar />
          <main className='pb-8'>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
